name: Run Tests

on: 
  push: 
    branches:
      - '**'
      - '!master'

jobs:
  run-tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Run npm ci
        run: npm ci
        env:
          NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run Jest
        run: npm run test
